version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # user
    environment:
        NEXT_PUBLIC_API_URL: "http://localhost:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # server
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
